import Link from 'next/link';
import renderHTML from 'react-render-html';
import moment from 'moment';
import { API } from '../../config';

const FlipCard = ({ car }) => {
    const showBlogCategories = blog =>
        blog.categories.map((c, i) => (
            <Link key={i} href={`/categories/${c.slug}`}>
                <a className="btn btn-primary mr-1 ml-1 mt-3">{c.name}</a>
            </Link>
        ));

    const showBlogTags = blog =>
        blog.tags.map((t, i) => (
            <Link key={i} href={`/tags/${t.slug}`}>
                <a className="btn btn-outline-primary mr-1 ml-1 mt-3">{t.name}</a>
            </Link>
        ));

    const getFeaturedImage = blog => {
        let url = blog.autoGenerated ? blog.product_imgurl : `${API}/blog/photo/${blog.slug}`;
        return url.replace(".jpg", ".SL375.jpg"); 
    }
        

    return (
        //new
        <div className="flip flip-horizontal">
            <div
                className="front"
                style={{
                    backgroundImage:
                        'url(' +
                        getFeaturedImage(blog) +
                        ')'
                }}
            >
                <h2 className="text-shadow text-center h1"></h2>
            </div>
            <div className="back text-center">
                <Link href={`/blogs/${blog.slug}`}>    
                    <h6 className="pt-3 pb-3 font-weight-bold">{blog.title}</h6>
                </Link>
                <Link href={`/blogs/${blog.slug}`}>
                     <a className="btn btn-primary pt-2">Read more</a>
                </Link>
            </div>
        </div>
    );
};

export default FlipCard;